package at.aau.hexabrawl.websocketserver.model

enum class ErrorCode {
    NOT_YOUR_TURN,
    INVALID_MOVE,
    GAME_FULL,
    GAME_NOT_STARTED,
    INSUFFICIENT_GOLD,
    COLOR_ALREADY_TAKEN,
    ROOM_NOT_FOUND,
    INVALID_PLACEMENT,
    CHEAT_ALREADY_USED,
    CHEAT_ALREADY_PENDING,
    INVALID_CHEAT_DELTA,
    NO_PENDING_GIFT,
    OWNER_CANNOT_STEAL,
    GIFT_PENDING,
    RECONNECT_REJECTED
}
