services:
  server:
    image: ghcr.io/hexabrawl/server:latest
    restart: unless-stopped
    ports:
      - "53216:8080"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
        reservations:
          cpus: "0.5"
          memory: 768M
